In [1]:
import pandas as pd
import numpy as np
import warnings
from binerizer import *

In [2]:
credit = pd.read_csv('data/credit.csv')
credit

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,Y
0,b,30.83,0.000,u,g,w,v,1.25,False,False,1,False,g,202,0,True
1,a,58.67,4.460,u,g,q,h,3.04,False,False,6,False,g,43,560,True
2,a,24.50,0.500,u,g,q,h,1.50,False,False,0,False,g,280,824,True
3,b,27.83,1.540,u,g,w,v,3.75,False,False,5,False,g,100,3,True
4,b,20.17,5.625,u,g,w,v,1.71,False,False,0,False,s,120,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,b,21.08,10.085,y,p,e,h,1.25,False,False,0,False,g,260,0,False
649,a,22.67,0.750,u,g,c,v,2.00,False,False,2,False,g,200,394,False
650,a,25.25,13.500,y,p,ff,ff,2.00,False,False,1,False,g,200,1,False
651,b,17.92,0.205,u,g,aa,v,0.04,False,False,0,False,g,280,750,False
652,b,35.00,3.375,u,g,c,h,8.29,False,False,0,False,g,0,0,False

In [3]:
binerizeData(credit, verbose = True)

Column X1: Applying 1 Hot Encoding.
Column X2: Binarzing with specified numeric strategy.
Column X3: Binarzing with specified numeric strategy.
Column X4: Applying 1 Hot Encoding.
Column X5: Applying 1 Hot Encoding.
Column X6: Applying 1 Hot Encoding.
Column X7: Applying 1 Hot Encoding.
Column X8: Binarzing with specified numeric strategy.
Column X9: Copying to final dataframe.
Column X10: Copying to final dataframe.
Column X11: Binarzing with specified numeric strategy.
Column X12: Copying to final dataframe.
Column X13: Applying 1 Hot Encoding.
Column X14: Binarzing with specified numeric strategy.
Column X15: Binarzing with specified numeric strategy.
Column Y: Copying to final dataframe.

,X1_a,X1_b,X1_a,X1_b,X2_19.17*,X2_21.53*,X2_23.25*,X2_25.42*,X2_28.42*,X2_32.08*,...,X15_246.4*,X15_606.0*,X15_2000.0*,X15_0.0_,X15_5.0_,X15_50.0_,X15_246.4_,X15_606.0_,X15_2000.0_,Y
0,False,True,True,False,False,False,False,False,False,True,...,True,True,True,False,False,False,False,False,False,True
1,True,False,False,True,False,False,False,False,False,False,...,False,True,True,True,True,True,True,False,False,True
2,True,False,False,True,False,False,False,True,True,True,...,False,False,True,True,True,True,True,True,False,True
3,False,True,True,False,False,False,False,False,True,True,...,True,True,True,True,False,False,False,False,False,True
4,False,True,True,False,False,True,True,True,True,True,...,True,True,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,False,True,True,False,False,True,True,True,True,True,...,True,True,True,False,False,False,False,False,False,False
649,True,False,False,True,False,False,True,True,True,True,...,False,True,True,True,True,True,True,False,False,False
650,True,False,False,True,False,False,False,True,True,True,...,True,True,True,True,False,False,False,False,False,False
651,False,True,True,False,True,True,True,True,True,True,...,False,False,True,True,True,True,True,True,False,False
652,False,True,True,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False